# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questionreponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('reponse_text', models.CharField(max_length=200)),
                ('pub_date_theme', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_text', models.CharField(max_length=200)),
                ('pub_date_theme', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.AddField(
            model_name='questionreponse',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appfaq.Theme'),
        ),
    ]
