# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 19:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appfaq', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionreponse',
            old_name='pub_date_theme',
            new_name='pub_date_questionreponse',
        ),
    ]
